### ISSUE TITLE
Suggestion: Rainbow 6 Siege stats lookup

### ISSUE THREAD

**Issue by JoshuaACasey** [dbkynd/armorybot#29]

**Comment by dbkynd** [comment]
I did it! anneYay

**Comment by JoshuaACasey** [comment]
"21 hours ago". I just looked at the command list today to remind me what commands the bot has. What a coincidence!
anneYay Thanks!

I don't want to be an annoying bitch, but would it be possible to include more info (see this example: http://prntscr.com/fazoro )
